name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - '**/*.md'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código 
        uses: actions/checkout@v3

      - name: 🔐 Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_GUILHERME_USERNAME }}
          password: ${{ secrets.DOCKERHUB_GUILHERME_ACCESS_TOKEN }}

      - name: 🛠️ Build da imagem do ms-categoria do App Lanchonete
        run: |
          docker build \
          --build-arg MODE=prod \
          --build-arg PROFILE=prod \
          -t ${{ secrets.DOCKERHUB_GUILHERME_USERNAME }}/fiap-tech-challenge-lanchonete-ms-categoria:latest \
          -f Dockerfile .

      - name: 🚀 Push da imagem do ms-categoria dp App Lanchonete
        run: |
          docker push ${{ secrets.DOCKERHUB_GUILHERME_USERNAME }}/fiap-tech-challenge-lanchonete-ms-categoria:latest
